services:
  app:
    image: salkin263/netflix-clone:1.7.2
    container_name: netflix-clone
    ports:
      - "3000:3000"
    volumes:
      - /movies:/movies
      - /series:/series
    restart: unless-stopped